---
title: "Fig.2E. Principal sensory trigeminal nucleus"
author: "Evgenii O. Tretiakov"
date: "`r Sys.Date()`"
output:
  workflowr::wflow_html:
    toc: true
---

```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(
  autodep        = TRUE,
  cache          = FALSE,
  cache.lazy     = FALSE,
  dev            = c("png", "pdf"),
  echo           = TRUE,
  error          = FALSE,
  fig.align      = "center",
  fig.width      = 14,
  fig.height     = 12,
  message        = FALSE,
  warning        = FALSE
)
Sys.setenv(RETICULATE_PYTHON = "/opt/python/3.8.8/bin/python")
# Load tidyverse infrastructure packages
suppressPackageStartupMessages({
  library(here)
  library(RColorBrewer)
  library(viridis)
  library(tidyverse)
  library(magrittr)
  library(stringr)
  library(skimr)
  library(future)
  library(zeallot)
  library(kableExtra)
  library(reticulate)
})
reticulate::use_condaenv("/opt/python/3.8.8/bin/python")

suppressPackageStartupMessages({
  library(Seurat)
  library(SeuratWrappers)
  library(SeuratDisk)
  library(sctransform)
  library(glmGamPoi)
  library(patchwork)
  library(UpSetR)
  library(ggstatsplot)
  library(qs)
  library(Scillus)
  library(scCustomize)
  library(Nebulosa)
  library(mrtree)
  library(gprofiler2)
})

# Set paths
src_dir    <- here('code')
data_dir   <- here('data')
output_dir <- here('output')
plots_dir  <- here(output_dir, 'figures')
tables_dir <- here(output_dir, 'tables')
source(here(src_dir, 'genes.R'))
source(here(src_dir, 'functions.R'))

# parallelisation
n_cores <- 16
plan(multisession, workers = n_cores)
options(future.globals.maxSize = 400000 * 1024^2) # 400Gb


# set seed
reseed <- 42
set.seed(seed = reseed)

# ggplot2 theme
theme_set(ggmin::theme_powerpoint())

```


Load dataset

```{r load}
srt <- LoadH5Seurat(here(data_dir, "Pr5P7_clusters.h5Seurat"))
Idents(srt) <- "sep_clstr"
neurons <- subset(srt, subset = Rbfox3 > 0 | Elavl4 > 0 | Snap25 > 0 | Stmn2 > 0)
gneurons <- subset(neurons, subset = Galr1 > 0)
```

We check list of genes based on our prior knowledge.

```{r}
gene_of_interest <-
  c("Gal", "Galr1", "Galr2", "Galr3", 
    "Ntn1", "Ntn2", "Ntn3", "Ntn4", "Ntn5", 
    "Slit1", "Dcc",
    "Prkaca", "Adcy1", "Grin1", 
    "Oxt", "Npy", "Sst", "Avp")

genes_present <- Gene_Present(data = srt, gene_list = gene_of_interest)
genes_present
```

```{r pl-dotplot-all-rna, fig.align='center', fig.width=8, fig.asp = 0.618}
DotPlot_scCustom(
  seurat_object = srt,
  assay = "RNA",
  features = genes_present$found_features,
  flip_axes = TRUE,
  x_lab_rotate = TRUE,
  colors_use = viridis(n = 30, alpha = .75, direction = -1, option = "E"))
```

```{r pl-clusters, fig.align='center', fig.width=7, fig.asp = 0.618}
DimPlot_scCustom(
  srt,
  label = TRUE,
  repel = TRUE,
  pt.size = 2,
  figure_plot = TRUE
  ) + ggtitle("Clusters") + NoLegend()
```



```{r drv-sbs-mtx-neurons}
sbs_mtx_neuro <-
    neurons[["RNA"]]$data %>%
    as.data.frame() %>%
    t()
rownames(sbs_mtx_neuro) <- colnames(neurons)

# Filter features
filt_low_genes2 <-
    colSums(sbs_mtx_neuro) %>%
    .[. > quantile(., 0.01)] %>%
    names()
sbs_mtx_neuro %<>% .[, filt_low_genes2]

min_filt_vector2 <-
    sbs_mtx_neuro %>%
    as_tibble() %>%
    select(all_of(filt_low_genes2)) %>%
    summarise(across(.fns = ~ quantile(.x, .005))) %>%
    as.list %>%
    map(as.double) %>%
    simplify %>%
    .[filt_low_genes2]

# Prepare table of intersection sets analysis
content_sbs_mtx_neuro <-
    (sbs_mtx_neuro > min_filt_vector2) %>%
    as_tibble() %>%
    mutate_all(as.numeric)


neurons$gaba_status <-
  content_sbs_mtx_neuro %>%
  select(Gad1, Gad2, Slc32a1) %>%
  mutate(gaba = if_all(.fns = ~ .x > 0)) %>%
  .$gaba

neurons$gaba_expr <-
  content_sbs_mtx_neuro %>%
  select(Gad1, Gad2, Slc32a1) %>%
  mutate(gaba = if_any(.fns = ~ .x > 0)) %>%
  .$gaba

neurons$glut_status <-
  content_sbs_mtx_neuro %>%
  select(Slc17a6) %>%
  mutate(glut = Slc17a6 > 0) %>%
  .$glut

neuro_fin <-
  subset(neurons,
    cells = union(
      WhichCells(neurons,
        expression = gaba_status == TRUE & glut_status == FALSE),
      WhichCells(neurons,
        expression = glut_status == TRUE & gaba_expr == FALSE)))

neuro_fin$status <- neuro_fin$gaba_status %>%
  if_else(true = "GABAergic",
    false = "glutamatergic")
Idents(neuro_fin) <- "status"

sbs_mtx_neuro <-
    neuro_fin[["RNA"]]$data %>%
    as.data.frame() %>%
    t()
rownames(sbs_mtx_neuro) <- colnames(neuro_fin)

# Filter features
filt_low_genes2 <-
    colSums(sbs_mtx_neuro) %>%
    .[. > quantile(., 0.01)] %>%
    names()
sbs_mtx_neuro %<>% .[, filt_low_genes2]

min_filt_vector2 <-
    sbs_mtx_neuro %>%
    as_tibble() %>%
    select(all_of(filt_low_genes2)) %>%
    summarise(across(.fns = ~ quantile(.x, .005))) %>%
    as.list %>%
    map(as.double) %>%
    simplify %>%
    .[filt_low_genes2]

# Prepare table of intersection sets analysis
content_sbs_mtx_neuro <-
    (sbs_mtx_neuro > min_filt_vector2) %>%
    as_tibble() %>%
    mutate_all(as.numeric)

```


```{r plot-piecharts-sbs-neuro-chisqr, fig.width=6.5, fig.asp=0.618}

sbs_mtx_neuro_full <- content_sbs_mtx_neuro |> 
  select(any_of(c(neurotrans, glutr, gabar, "Gal", "Galr1"))) |> 
  dplyr::bind_cols(neuro_fin@meta.data)

sbs_mtx_neuro_full |> glimpse()

sbs_mtx_neuro_full$Gal_sign <- 
  sbs_mtx_neuro_full %>%
  select(Galr1) %>%
  mutate(Gal_sign = if_any(.fns = ~ .x > 0)) %>%
  .$Gal_sign

# for reproducibility
set.seed(reseed)
# plot
ggpiestats(
  # arguments relevant for `ggpiestats()`
  data = sbs_mtx_neuro_full |> filter(status == "glutamatergic"),
  x = Gal_sign,
  perc.k = 1,
  package = "ggsci",
  palette = "category10_d3",
  # arguments relevant for `combine_plots()`
  title.text = "Molecular specification of Pr5 neuronal lineages by Galr1 signalling and main glutamatergic neurotransmitter expression",
  caption.text = "Asterisks denote results from proportion tests; \n***: p < 0.001, ns: non-significant",
  plotgrid.args = list(nrow = 1)
)
```
Molecular specification of Pr5 neuronal lineages by Galr1 signalling and main glutamatergic neurotransmitter expression (no GABAergic cells express Galr1)


```{r pl-feature-slc17a6, fig.align='center', fig.width=7, fig.asp = 0.618}
p1 <- FeaturePlot_scCustom(
  srt, "Slc17a6",
  pt.size = 2,
  order = TRUE,
  alpha_exp = 0.65,
  alpha_na_exp = 0.2,
  label = TRUE,
  repel = TRUE,
  colors_use = srt@misc$expr_Colour_Pal) + 
  ggtitle("Slc17a6(Vglut2): ") + theme(plot.title = element_text(size = 24))
p1
```

```{r pl-density-slc17a6, fig.align='center', fig.width=7, fig.asp = 0.618}
SCpubr::do_NebulosaPlot(sample = srt, features = "Slc17a6")
```
```{r pl-density-galr1, fig.align='center', fig.width=7, fig.asp = 0.618}
SCpubr::do_NebulosaPlot(sample = srt, features = "Galr1")
```

```{r pl-density-slc17a6-Galr1, fig.align='center', fig.width=7, fig.asp = 0.618}
SCpubr::do_NebulosaPlot(
  sample = srt,
  features = c("Slc17a6", "Galr1"),
  joint = TRUE, 
  return_only_joint = TRUE,
  plot.title = "Joint density Slc17a6(Vglut2) + Galr1")
```

```{r}
srt_vglut2 <- subset(srt, idents = c(1, 2, 3, 4, 5, 6, 9))
srt_vglut2 <- subset(srt_vglut2, subset = UMAP_1 > -6 & UMAP_1 < 9)
```

```{r pl-feature-Galr1, fig.align='center', fig.width=8, fig.asp = 0.618}
p2 <- FeaturePlot_scCustom(
  srt_vglut2, "Galr1",
  pt.size = 5,
  order = TRUE,
  alpha_exp = 0.75,
  alpha_na_exp = 0.05,
  colors_use = srt@misc$expr_Colour_Pal) + 
  ggtitle("Galr1 in Vglut2+ populations") + theme(plot.title = element_text(size = 24))
p2
```

```{r pl-density-Galr1, fig.align='center', fig.width=7, fig.asp = 0.618}
SCpubr::do_NebulosaPlot(
  sample = srt_vglut2,
  features = c("Galr1"),
  plot.title = "Galr1 across Vglut cell-populations only")
```

```{r pl-density-Galr1-across-vglut2, fig.align='center', fig.width=7, fig.asp = 0.618}
SCpubr::do_NebulosaPlot(
  sample = srt_vglut2,
  features = c("Slc17a6", "Galr1"),
  joint = TRUE, 
  return_only_joint = TRUE,
  plot.title = "Joint density Slc17a6 + Galr1 across Vglut cells")
```

```{r pl-clusters-glut2, fig.align='center', fig.width=7, fig.asp = 0.618}
DimPlot_scCustom(
  srt_vglut2,
  label = TRUE,
  repel = TRUE,
  pt.size = 3,
  figure_plot = TRUE
  ) + ggtitle("Vglut2+ clusters") + NoLegend()
```

```{r pl-heatmap-vglut, fig.align='center', fig.width=8, fig.asp = 0.618}
DoHeatmap(srt_vglut2, features = genes_present$found_features)
```

```{r pl-dotplot-vglut2-rna, fig.align='center', fig.width=5, fig.asp = 0.618}
p3 <- DotPlot_scCustom(
  seurat_object = srt_vglut2,
  assay = "RNA",
  features = genes_present$found_features,
  flip_axes = TRUE,
  x_lab_rotate = TRUE,
  dot.min = .01,
  dot.scale = 10,
  colors_use = viridis(n = 30, alpha = .75, direction = -1, option = "E"))
p3
```

```{r pl-stckvlnplot-vglut-rna, fig.align='center', fig.width=6, fig.height=7.416}
p4 <- Stacked_VlnPlot(
  seurat_object = srt_vglut2,
  assay = "RNA",
  features = genes_present$found_features,
  x_lab_rotate = F
)
p4
```

```{r pl-fig-2d, fig.align='center', fig.width=18, fig.asp = 0.206}
p1 | p2 | p3
```

```{r pl-fig2d-alt, fig.align='center', fig.width=12, fig.height=7.416}
(p1 / p2) | p4
```

```{r}
library(org.Mm.eg.db)
library(AnnotationDbi)
library(clusterProfiler)

# Define the GO IDs
go_ids <- c(
  'GO:0007411',  # axon guidance
  'GO:0007409',  # axonogenesis
  'GO:0030426',  # growth cone
  'GO:0021860',  # pyramidal neuron development
  'GO:0097490',  # sympathetic neuron projection extension
  'GO:1990138',  # neuron projection extension
  'GO:0010976',  # positive regulation of neuron projection development
  'GO:0010977',  # negative regulation of neuron projection development
  'GO:0021952')  # central nervous system projection neuron axonogenesis

# Initialize a list to store gene symbols for each GO term
gene_symbols_list <- list()

# Fetch gene symbols for each GO term
for(i in seq_along(go_ids)) {
  gene_ids <-
    AnnotationDbi::select(
      org.Mm.eg.db,
      keys = go_ids[i],
      columns = "ENTREZID",
      keytype = "GO"
    )
  gene_symbols <-
    mapIds(
      org.Mm.eg.db,
      keys = gene_ids$ENTREZID,
      column = "SYMBOL",
      keytype = "ENTREZID",
      multiVals = "first"
    )
  gene_symbols_list[[go_ids[i]]] <- gene_symbols
}

gene_symbols_list %<>% map(unique)

GetGoMatrix <- function(genes) {
  e <- t(as.matrix(srt_vglut2[["SCT"]]$data[
    srt_vglut2[["SCT"]]$data %>%
      rowSums() %>%
      .[. > 1] %>%
      names() %>%
      .[. %in% genes],
  ]))
  return(e)
}

go_matrixes <- gene_symbols_list |> map(GetGoMatrix)

# Print the gene symbols for each GO term
for (i in seq_along(gene_symbols_list)) {
  print(paste("GO ID:", names(gene_symbols_list[i])))
  print(gene_symbols_list[[i]])
}

genes_keep <- gene_symbols_list |> purrr::reduce(c) |> unique()
```

```{r}
srt_vglut2$Galr1_expression <- srt_vglut2[["RNA"]]$counts["Galr1",] > 0
srt_vglut2$vglut2_expression <- srt_vglut2[["RNA"]]$counts["Slc17a6",] > 0
srt_vglut2_galr1 <- subset(srt_vglut2, subset = Galr1_expression)
bulk_all <- Matrix::rowSums(srt_vglut2[["RNA"]]$counts != 0)/ncol(srt_vglut2)
bulk_vglut2_galr1 <- Matrix::rowSums(srt_vglut2_galr1[["RNA"]]$counts != 0)/ncol(srt_vglut2_galr1)
genes_keep %<>% .[. %in% names(bulk_all)]
write_excel_csv(data.frame("gene" = names(bulk_all), "vglut2_clusters" = bulk_all, "galr1" = bulk_vglut2_galr1), here(tables_dir, "bulk_vglut2_clusters_expression.csv"))
write_excel_csv(data.frame("gene" = names(bulk_all), "vglut2_clusters" = bulk_all, "galr1" = bulk_vglut2_galr1)[genes_keep,], here(tables_dir, "bulk_vglut2_clusters_expression_subset.csv"))

srt_vglut2$Galr1_expression <- ifelse(srt_vglut2$Galr1_expression, "Galr1+", "Galr1-")
srt_vglut2$vglut2_expression <- ifelse(srt_vglut2$vglut2_expression, "Vglut2+", "Vglut2-")
srt_vglut2$status <- str_c(srt_vglut2$vglut2_expression, srt_vglut2$Galr1_expression, sep = "_")
library(scBubbletree)
A <- Embeddings(srt_vglut2[["pca"]])
m <- srt_vglut2@meta.data

bubbletree <- scBubbletree::get_bubbletree_dummy(
  x = A,
  cs = as.vector(srt_vglut2$status),
  B = 200,
  N_eff = 200,
  cores = n_cores,
  round_digits = 1
)
bubbletree$tree
```


```{r pl-bubbletree-exp-axon-guidance}
bubbletree$tree
  scBubbletree::get_num_tiles(btd = bubbletree,
                    fs = go_matrixes[["GO:0007411"]],
                    summary_function = "pct nonzero",
                    x_axis_name = 'Gene expression',
                    rotate_x_axis_labels = TRUE,
                    round_digits = 1,
                    tile_text_size = 2.75)$plot
```


```{r pl-bubbletree-exp-axonogenesis}
bubbletree$tree
  scBubbletree::get_num_tiles(btd = bubbletree,
                    fs = go_matrixes[["GO:0007409"]],
                    summary_function = "pct nonzero",
                    x_axis_name = 'Gene expression',
                    rotate_x_axis_labels = TRUE,
                    round_digits = 1,
                    tile_text_size = 2.75)$plot
```


```{r pl-bubbletree-exp-growth-cone}
bubbletree$tree
  scBubbletree::get_num_tiles(btd = bubbletree,
                    fs = go_matrixes[["GO:0030426"]],
                    summary_function = "pct nonzero",
                    x_axis_name = 'Gene expression',
                    rotate_x_axis_labels = TRUE,
                    round_digits = 1,
                    tile_text_size = 2.75)$plot
```


```{r pl-bubbletree-exp-pyramidal-neuron-development}
bubbletree$tree
  scBubbletree::get_num_tiles(btd = bubbletree,
                    fs = go_matrixes[["GO:0021860"]],
                    summary_function = "pct nonzero",
                    x_axis_name = 'Gene expression',
                    rotate_x_axis_labels = TRUE,
                    round_digits = 1,
                    tile_text_size = 2.75)$plot
```


```{r pl-bubbletree-exp-sympathetic-neuron-projection-extension}
bubbletree$tree
  scBubbletree::get_num_tiles(btd = bubbletree,
                    fs = go_matrixes[["GO:0097490"]],
                    summary_function = "pct nonzero",
                    x_axis_name = 'Gene expression',
                    rotate_x_axis_labels = TRUE,
                    round_digits = 1,
                    tile_text_size = 2.75)$plot
```


```{r pl-bubbletree-exp-neuron-projection-extension}
bubbletree$tree
  scBubbletree::get_num_tiles(btd = bubbletree,
                    fs = go_matrixes[["GO:1990138"]],
                    summary_function = "pct nonzero",
                    x_axis_name = 'Gene expression',
                    rotate_x_axis_labels = TRUE,
                    round_digits = 1,
                    tile_text_size = 2.75)$plot
```


```{r pl-bubbletree-exp-positive-regulation-of-neuron-projection-development}
bubbletree$tree
  scBubbletree::get_num_tiles(btd = bubbletree,
                    fs = go_matrixes[["GO:0010976"]],
                    summary_function = "pct nonzero",
                    x_axis_name = 'Gene expression',
                    rotate_x_axis_labels = TRUE,
                    round_digits = 1,
                    tile_text_size = 2.75)$plot
```


```{r pl-bubbletree-exp-negative-regulation-of-neuron-projection-development}
bubbletree$tree
  scBubbletree::get_num_tiles(btd = bubbletree,
                    fs = go_matrixes[["GO:0010977"]],
                    summary_function = "pct nonzero",
                    x_axis_name = 'Gene expression',
                    rotate_x_axis_labels = TRUE,
                    round_digits = 1,
                    tile_text_size = 2.75)$plot
```


```{r pl-bubbletree-exp-central-nervous-system-projection-neuron-axonogenesis}
bubbletree$tree
  scBubbletree::get_num_tiles(btd = bubbletree,
                    fs = go_matrixes[["GO:0021952"]],
                    summary_function = "pct nonzero",
                    x_axis_name = 'Gene expression',
                    rotate_x_axis_labels = TRUE,
                    round_digits = 1,
                    tile_text_size = 2.75)$plot
```
